### ISSUE TITLE
Drag anywhere?

### ISSUE THREAD

**Issue by cassidyjames** [danrabbit/harvey#7]
Similar problem with Nimbus; it's not clear where the titlebar ends, so any blank space should probably be draggable.

**Comment by danirabbit** [comment]
Yeah the problem I had with the code that nimbus uses for this is that it steals clicks inside of entries, which makes it hard to select text. So I need to figure out a way around that

**Comment by danirabbit** [comment]
Solved now that we use Hdy.Window
